report_homepage:
    path:     /admin/report
    defaults: { _controller: ReportBundle:Report:index }

report_create:
    path:      /report/create
    defaults:  { _controller: ReportBundle:Report:createReport }

report_display:
    path:      /admin/report/{id}
    defaults:  { _controller: ReportBundle:Report:displayReport }
    requirements:
      id:    \d+

report_ban:
    path:       /admin/report/ban
    defaults:   { _controller: ReportBundle:Report:banUser }