<?php

namespace BottleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BottleAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BottleAdminRepository extends EntityRepository
{


    public function getAdminBottlesCollected($userConnected)
    {
        $bottles = $this->findByFkReceiver($userConnected);
        $allBottles = [];
        foreach ($bottles as $bottle) {
            if ($bottle->getFkTransmitter()->getId() !== $userConnected->getId() && $bottle->getState() == 3) {
                $allBottles[] = $bottle;
            }
        }
        return $allBottles;
    }
}
