<?php

namespace BottleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BottleAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BottleAdminRepository extends EntityRepository
{
}
