<?php

namespace BottleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BottleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BottleRepository extends EntityRepository
{
}
