<?php

namespace BottleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmojiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmojiRepository extends EntityRepository
{
}
