main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Main:index }

login:
    pattern:   /login
    defaults:  { _controller: MainBundle:Main:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout