main_home:
    path:     /
    defaults: { _controller: MainBundle:Main:index }

login:
    pattern:   /login
    defaults:  { _controller: MainBundle:Main:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

register:
    pattern:   /register
    defaults:  { _controller: MainBundle:Main:register }

register_check:
    pattern:   /register_check
    defaults:  { _controller: MainBundle:Main:registerCheck }