bottle_home:
    path:     /bottle
    defaults: { _controller: BottleBundle:Bottle:index }

bottle_open:
  path:        /bottle/open
  defaults: { _controller: BottleBundle:Bottle:openBottle }

bottle_write:
  path:        /bottle/write
  defaults: { _controller: BottleBundle:Bottle:writeBottle }

bottle_evaluate:
  path:        /bottle/evaluate
  defaults: { _controller: BottleBundle:Bottle:evaluateBottle }

bottle_create:
  path:        /bottle/create
  defaults: { _controller: BottleBundle:Bottle:createBottle }

# ----------

bottle_home_admin:
  path:        /admin
  defaults: { _controller: BottleBundle:Bottle:indexAdmin }

bottle_write_admin:
  path:        /admin/bottle/write
  defaults: { _controller: BottleBundle:Bottle:writeBottleAdmin }

bottle_create_admin:
  path:        /admin/bottle/create
  defaults: { _controller: BottleBundle:Bottle:createBottleAdmin }