bottle_home:
    path:     /bottle
    defaults: { _controller: BottleBundle:Bottle:index }

bottle_open:
  path:        /bottle/open
  defaults: { _controller: BottleBundle:Bottle:openBottle }

bottle_write:
  path:        /bottle/write
  defaults: { _controller: BottleBundle:Bottle:writeBottle }