collection_homepage:
    path:     /
    defaults: { _controller: CollectionBundle:Collection:index }


archived_bottles:
  path:        /Collection/archived
  defaults: { _controller: CollectionBundle:Collection:getCollection }