collection_home:
    path:     /collection
    defaults: { _controller: CollectionBundle:Collection:index }

collection_display_bottle:
    path:     /collection/display/bottle/{id}
    defaults: { _controller: CollectionBundle:Collection:displaySavedBottle }
    requirements:
        id: \d+

collection_display_bottle_admin:
    path:     /collection/display/bottle_admin/{id}
    defaults: { _controller: CollectionBundle:Collection:displaySavedBottleAdmin }
    requirements:
        id: \d+

collection_delete_bottle:
    path:     /collection/delete/bottle
    defaults: { _controller: CollectionBundle:Collection:deleteBottle }

collection_delete_bottle_admin:
    path:     /collection/delete/bottle_admin
    defaults: { _controller: CollectionBundle:Collection:deleteBottleAdmin }