collection_home:
    path:     /collection
    defaults: { _controller: CollectionBundle:Collection:index }

collection_display_bottle:
    path:     /collection/display/bottle/{id}
    defaults: { _controller: CollectionBundle:Collection:displaySavedBottle }
    requirements:
        id: \d+

collection_display_bottle_admin:
    path:     /collection/display/bottle_admin/{id}
    defaults: { _controller: CollectionBundle:Collection:displaySavedBottleAdmin }
    requirements:
        id: \d+

collection_delete:
    path:     /collection/delete
    defaults: { _controller: CollectionBundle:Collection:delete }
